databases:
  - name: search_real_time
    databaseName: search_real_time_production
    user: search_real_time

services:
  - type: web
    name: mysite
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: search_real_time
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false